### PR TITLE
Patch/formatting bug

### PR DESCRIPTION
**Pull request by winston**
For parsing and formatting of datetime value to be correct, the picker format and the display format is required to be the same. Hence hardcode the values into datetimepicker input. 

However, use `extra_formats` so that user can still override with their custom format via `input_html`.

### CODE REVIEW

**Comment by winston** [comment]
- [ ] release new version

**Comment by choonkeat** [comment]
> However, use extra_formats so that user can still override with their custom format via input_html.

From my understanding
- `format` remains the definitive input/output format
- whilst `extraFormats` only make input parsing lenient / liberal, e.g. when `date_extra_formats: [ 'DD.MM.YY' ]` then user can also enter `10.01.13` and it will be auto converted to `format` onBlur

To illustrate, using this branch without any config
- the javascript sets the input field to something like `10/25/2015 12:00 AM` (notice the format is not based on `picker_pattern`)
- when we form post to Rails to save into db, `10/25/2015 12:00 AM` would be invalid and be treated as `nil`

However, if we `reverse_merge!(date_format: ...)`  then
- the input value is `2015-10-25 00:00`
- when submitted to rails, the value is properly parsed and accepted as a `DateTime`

:. `format` is still what we have to provide by default, not `date_extra_formats`

(In any case, to allow override, there is no need to use a different key. `reverse_merge!(date_format: ...)` would suffice to let user give their own `date_format` or rely on our default)

--

However, there's still an issue with timezone.

The example above, Rails would store the value as `2015-10-25 00:00:00 UTC` given the default timezone `config.time_zone = 'UTC'`. If we display the value back to user via `local_time` (or server side timezone conversion) it would show `October 25, 2015 8:00am` which is not what the user (me) entered.

So the correct `picker_pattern` should be `YYYY-MM-DD HH:mm ZZ` and `display_pattern` should be `%Y-%m-%d %H:%M %z`

Then when I perform the example above
- the input value is `2015-10-25 00:00 +0800`
- when submitted to rails, the value is properly parsed and accepted as a `DateTime`
  - additionally, it would be correctly converted to UTC then saved as `2015-10-24 16:00:00 UTC`

When we display this value back to user via `local_time` (or server side timezone conversion) it would show `October 25, 2015 12:00am ` which is finally correct.

``` diff
diff --git a/app/inputs/date_time_picker_input.rb b/app/inputs/date_time_picker_input.rb
index 09f856a..e3abdc0 100644
--- a/app/inputs/date_time_picker_input.rb
+++ b/app/inputs/date_time_picker_input.rb
@@ -18,7 +18,7 @@ class DateTimePickerInput < SimpleForm::Inputs::StringInput
     input_html_options[:type] = "text"
 
     input_html_options[:data] ||= {}
-    input_html_options[:data].reverse_merge!(date_extra_formats: [picker_pattern])
+    input_html_options[:data].reverse_merge!(date_format: picker_pattern)
 
     input_html_options[:value] ||= I18n.localize(attr_value, format: display_pattern) if attr_value.present?
 
@@ -40,11 +40,11 @@ class DateTimePickerInput < SimpleForm::Inputs::StringInput
   private
 
     def display_pattern
-      "%Y-%m-%d %H:%M"
+      "%Y-%m-%d %H:%M %z"
     end
 
     def picker_pattern
-      "YYYY-MM-DD HH:mm"
+      "YYYY-MM-DD HH:mm ZZ"
     end
 
     def attr_value
```

**Comment by choonkeat** [comment]
Sorry, fixed the patch to allow "editing existing value" to work if the user does customize `format` (and `date_extra_formats`)

``` diff
diff --git a/app/inputs/date_time_picker_input.rb b/app/inputs/date_time_picker_input.rb
index 09f856a..6b43722 100644
--- a/app/inputs/date_time_picker_input.rb
+++ b/app/inputs/date_time_picker_input.rb
@@ -18,7 +18,9 @@ class DateTimePickerInput < SimpleForm::Inputs::StringInput
     input_html_options[:type] = "text"
 
     input_html_options[:data] ||= {}
-    input_html_options[:data].reverse_merge!(date_extra_formats: [picker_pattern])
+    input_html_options[:data].reverse_merge!(date_format: picker_pattern)
+    input_html_options[:data][:date_extra_formats] ||= []
+    input_html_options[:data][:date_extra_formats] << picker_pattern
 
     input_html_options[:value] ||= I18n.localize(attr_value, format: display_pattern) if attr_value.present?
 
@@ -40,11 +42,11 @@ class DateTimePickerInput < SimpleForm::Inputs::StringInput
   private
 
     def display_pattern
-      "%Y-%m-%d %H:%M"
+      "%Y-%m-%d %H:%M %z"
     end
 
     def picker_pattern
-      "YYYY-MM-DD HH:mm"
+      "YYYY-MM-DD HH:mm ZZ"
     end
 
     def attr_value
```

**Comment by choonkeat** [comment]
Unfortunately, whatever `format` user chooses MUST be rails compatible, otherwise it would still be rejected when form submit. So they can only effectively customize `date_extra_formats`

**Comment by winston** [comment]
I see what you are saying now! 

Actually this gem wasn't built to solve the "correct datetime go straight into db" problem and which is what all datepickers are not actually helping with.

Reason as follows.. 

Datetime pickers are all frontend stuff and they don't assume to know what happens in the backend. So, most datepickers are fully customizable in terms of format.. which means you can prefer to see "YYYY-MM-DD HH:MM" after you select a datetime or a designer may feel that a diff/clearer format of "DD JAN YYYY HH.MM" is nicer as a display. Hence datetime pickers allow that customizability.

However, then if you use such a iormat "DD JAN YYYY HH.MM", then it's really up to you on parsing the datetime in the backend.

So for us, an easy way is always to pick a format that Rails can recognize straight out of the box, which is "YYYY-MM-DD HH:mm A ZZ", then we don't need to do extra work behind the scene, so knowingly of what Rails does, we crafted the input format specially.

(But if this is a very public facing app, someone would probably complain soon that YYYY-MM-DD is ugly...)

----

To solve your problem and achieve "integration", the solution is just to add `input_html` like this, with my patch.

```
      = f.input :when, as: :date_time_picker, input_html: \
        { data: \
          { \
            date_format: "YYYY-MM-DD hh:mm A ZZ" \
          } \
        }
      = f.submit "Save", class: 'btn'
```

Then the data that goes in and out would be correct and as per what you expect.

Again, it's better to think of all these as just solving frontend stuff. Backend stuff should be handled separately, or knowingly as what I have suggested. Then the data would still be correct.

If you include timezone in the picker and display format, then it will affect JS parsing of the time. Attached gif.

ss

**Comment by winston** [comment]
Rewind. Let's have some sane defaults with this gem so that it works with Rails out of the box, and supposed we don't add any config, the datetime picker input should go into DB correctly with all details (i.e. year, month, day, hour, minute, second AND timezone). That's the base case for this gem. 

On top of that, since the [datetime_picker](https://github.com/Eonasdan/bootstrap-datetimepicker/commits/master) used in this gem allows for datetime format customization, you can still do it through `input_html`.

For example:
1. if we only want a date picker then `{ data: { date_format: 'YYYY-MM-DD' } }`.
2. If we want to modify the datetime format to '{ data { date_format: 'DD.MM.YYYY HH:mm: A } }'

And even if the form errors out, the date or datetime value will be preserved as what the user saw the first time when the date or datetime value was added.

However, we should add a note to the Readme and [Demo](datetime-picker-input.herokuapp.com) that in 2), we won't be able to guarantee what goes into the database. It is up the the developer to parse the data correctly that's coming in from the frontend (without timezone? sure?) and to display it as well. 

So, to achieve all the above, https://github.com/jollygoodcode/datetime_picker_input/commit/35c50c6173745e5f913ab346053b3ffc87724ba3 is enough.

Note: `extra_formats` doesn't help and just makes "preserve value on form error" wrong..

@choonkeat does this work?

**Comment by choonkeat** [comment]
yes i think this works 

tumblr_m3q5v3pvds1qgo8j0

**Pull request merged**
